# Generated by Django 4.1.5 on 2023-01-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('image', models.ImageField(upload_to='images', verbose_name='Обложка')),
                ('text', models.TextField(verbose_name='Текст')),
                ('genres', models.ManyToManyField(to='books.genre', verbose_name='Жанры')),
            ],
        ),
    ]
