# Generated by Django 4.1.5 on 2023-01-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='media/nopic.gif', upload_to='', verbose_name='Обложка'),
        ),
    ]
