# Generated by Django 4.1.5 on 2023-01-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='images/nopic.gif', upload_to='images', verbose_name='Обложка'),
        ),
    ]
